# Generated by Django 2.0.5 on 2020-10-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='url',
        ),
    ]
